import test from 'node:test';import assert from 'node:assert/strict';import {randomBytes,createHash} from 'node:crypto';
import {Store} from '../automation/service-bots/store.mjs';import {BUSINESSES} from '../automation/service-bots/config.mjs';
import {MARIA_TENANT,MARIA_COMPANY,MARIA_PROGRAM_URL} from '../automation/service-bots/maria-program.mjs';
import {initializeIntakeJournal,recordIntakeWebhook} from '../automation/service-bots/intake-journal.mjs';
import {installProgramSupervision,restoreProgramSupervision,programSupervisionStatus,dailyProgramCross} from '../automation/service-bots/program-supervision.mjs';
function fixture(){const now=Date.now(),c={company:'fumigacion',...BUSINESSES.fumigacion,lines:BUSINESSES.fumigacion.phones.map((phone,i)=>({phone,instance:'own-'+i})),mariaProgram:{enabled:true,token:'r'.repeat(43),actorId:'25b2e265-e463-4592-bab1-86b7b1687eae',startsAt:now-3600000,expiresAt:now+86400000}},s=new Store(':memory:',c.company,randomBytes(32));initializeIntakeJournal(s,c);const b={actorId:c.mariaProgram.actorId,token:'s'.repeat(43),startsAt:new Date(now-1000).toISOString(),expiresAt:new Date(now+3600000).toISOString(),url:MARIA_PROGRAM_URL+'/operational-audit'};return {c,s,b};}
const snapshot=(c,body)=>({company:'FUMIGACION',tenantId:MARIA_TENANT,companyId:MARIA_COMPANY,advisorMembershipId:c.mariaProgram.actorId,day:body.day,from:body.day+'T05:00:00.000Z',to:new Date(Date.parse(body.day+'T05:00:00Z')+86400000).toISOString(),readOnly:true,customerNotesWritesEnabled:false,coverage:{ordersComplete:true,techniciansComplete:true,auditsComplete:true},orders:[],technicians:[],deletions:[]});
test('separate audit access is verified read-only, encrypted, restored, and does not replace registration',async()=>{const {c,s,b}=fixture();try{const calls=[],fetcher=async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>snapshot(c,JSON.parse(options.body))};};const before=c.mariaProgram.token;await installProgramSupervision(c,s,b,fetcher);assert.equal(c.mariaProgram.token,before);assert.equal(calls[0].options.headers.Authorization,'Bearer '+b.token);assert.equal(calls[0].url,b.url);assert.equal(programSupervisionStatus(c).readOnly,true);assert.equal(programSupervisionStatus(c).customerNotesWritesEnabled,false);assert.doesNotMatch(s.db.prepare('SELECT value FROM meta WHERE key=?').get('maria-operational-audit-setup').value,new RegExp(b.token));const copy={...c,programSupervision:undefined};restoreProgramSupervision(copy,s);assert.equal(copy.programSupervision.token,b.token);assert.equal(s.db.prepare('SELECT COUNT(*) n FROM outbox').get().n,0);}finally{s.close();}});
test('registration token, foreign endpoint/actor, extended expiry and wrong company cannot configure read access',async()=>{const {c,s,b}=fixture();try{let calls=0;for(const patch of [{token:c.mariaProgram.token},{url:MARIA_PROGRAM_URL},{actorId:'other'},{expiresAt:new Date(c.mariaProgram.expiresAt+1).toISOString()}])await assert.rejects(installProgramSupervision(c,s,{...b,...patch},()=>{calls++;}));await assert.rejects(installProgramSupervision({...c,company:'servicio-tecnico'},s,b,()=>{calls++;}));assert.equal(calls,0);assert.equal(programSupervisionStatus(c).configured,false);}finally{s.close();}});
test('wrong backend scope and writable response never persist audit access',async()=>{const {c,s,b}=fixture();try{for(const patch of [{companyId:'foreign'},{customerNotesWritesEnabled:true},{readOnly:false},{advisorMembershipId:'foreign'}])await assert.rejects(installProgramSupervision(c,s,b,async()=>({ok:true,json:async()=>({...snapshot(c,{day:new Date(Date.now()-5*3600000).toISOString().slice(0,10)}),...patch})})));assert.equal(c.programSupervision,undefined);}finally{s.close();}});
test('daily audit without supervisory access remains partial, never declares missing orders or zero actual sales',async()=>{const {c,s}=fixture();try{let calls=0;const day=new Date(Date.now()-5*3600000).toISOString().slice(0,10),r=await dailyProgramCross(c,s,()=>{calls++;},{company:'fumigacion',day});assert.equal(calls,0);assert.equal(r.programReviewReason,'SEPARATE_PROGRAM_AUDIT_ACCESS_REQUIRED');assert.equal(r.coverage.programAvailable,false);assert.equal(r.coverage.paginationComplete,true);assert.equal(r.unmatchedContactsAreMissingServices,false);assert.equal(r.technicianProgress.completedStatus,'UNKNOWN');assert.equal(r.businessWrites,0);assert.equal(r.sends,0);}finally{s.close();}});
test('wrong snapshot day preserves available journal report rather than fail or borrow other day orders',async()=>{const {c,s,b}=fixture();try{const day=new Date(Date.now()-5*3600000).toISOString().slice(0,10);c.programSupervision={...b,startsAt:Date.parse(b.startsAt),expiresAt:Date.parse(b.expiresAt)};const r=await dailyProgramCross(c,s,async()=>({ok:true,json:async()=>({...snapshot(c,{day}),day:'2020-01-01'})}),{company:'fumigacion',day});assert.equal(r.programReviewReason,'PROGRAM_READ_NOT_VERIFIED');assert.equal(r.coverage.programAvailable,false);assert.equal(r.technicianProgress.completedStatus,'UNKNOWN');assert.match(r.reportText,/cruce|Meta de realización: cobertura/);}finally{s.close();}});

test('normalized current phones alone cannot certify a missing service after complete search',async()=>{
 const {c,s,b}=fixture();try{
  const now=Date.now(),day=new Date(now-5*3600000).toISOString().slice(0,10),phone='573001112233',line=c.lines[0];
  c.programSupervision={...b,startsAt:Date.parse(b.startsAt),expiresAt:Date.parse(b.expiresAt)};
  recordIntakeWebhook(s,c,{instance:line.instance,event:'messages.upsert',data:{key:{id:'AUDIT_CONTACT_001',remoteJid:phone+'@s.whatsapp.net',fromMe:false},messageTimestamp:now/1000,message:{conversation:'Quiero el servicio'}}},{authenticated:true,verifiedBinding:{phone:line.phone,instance:line.instance,ownerVerified:true,open:true},receivedAt:now});
  let searches=0;
  const fetcher=async(url,options)=>{const body=JSON.parse(options.body);if(url.endsWith('/contact-audit')){searches++;return {ok:true,json:async()=>({...snapshot(c,{day}),orders:[],searchedContacts:[{phone,complete:true,identityAmbiguous:false,orderIds:[]}],coverage:{contactSearchComplete:true,noncanonicalPhoneFieldsCovered:false}})};}return {ok:true,json:async()=>snapshot(c,body)};};
  const r=await dailyProgramCross(c,s,fetcher,{company:'fumigacion',day},now);
  assert.equal(searches,1);assert.equal(r.contacts.length,1);assert.equal(r.contacts[0].completeContactSearch,false);assert.notEqual(r.contacts[0].comparison,'NO_RECORD_AFTER_COMPLETE_CONTACT_SEARCH');assert.equal(r.contacts[0].missingServiceVerified,false);
 }finally{s.close();}
});
test('technical runtime reports no Fumigacion supervision guard or program actor',()=>{const r=programSupervisionStatus({company:'servicio-tecnico'});assert.equal(r.guard,null);assert.equal(r.companyId,null);assert.equal(r.actorId,null);assert.equal(r.configured,false);});
test('supervision is invalidated when registration is disabled or its actor/window changes',()=>{const {c,s,b}=fixture();try{c.programSupervision={...b,startsAt:Date.parse(b.startsAt),expiresAt:Date.parse(b.expiresAt)};assert.equal(programSupervisionStatus(c).enabled,true);for(const mariaProgram of [{...c.mariaProgram,enabled:false},{...c.mariaProgram,actorId:'other'},{...c.mariaProgram,expiresAt:c.programSupervision.expiresAt-1},{...c.mariaProgram,startsAt:c.programSupervision.startsAt+1},{...c.mariaProgram,token:b.token}])assert.equal(programSupervisionStatus({...c,mariaProgram}).enabled,false);}finally{s.close();}});
test('admin, webhook and proof grants cannot become general audit credentials',async()=>{const {c,s,b}=fixture();try{const hashed=createHash('sha256').update(b.token).digest('hex');for(const patch of [{authHash:hashed},{webhookHash:hashed},{retentionProofAccess:{tokenHash:hashed}}])await assert.rejects(installProgramSupervision({...c,...patch},s,b,()=>{throw Error('must not connect');}));s.company='servicio-tecnico';await assert.rejects(installProgramSupervision(c,s,b,()=>{}));assert.throws(()=>restoreProgramSupervision(c,s));}finally{s.close();}});
