import {test} from 'node:test';import assert from 'node:assert/strict';import {randomBytes} from 'node:crypto';
import {BUSINESSES,SANDRA,DIEGO} from '../automation/service-bots/config.mjs';
import {Store} from '../automation/service-bots/store.mjs';import {Engine} from '../automation/service-bots/engine.mjs';
import {customerActivity,chiefStatusTopic} from '../automation/service-bots/chief-status.mjs';import {decodeWebhook} from '../automation/service-bots/webhook.mjs';
function fixture(company='fumigacion'){const config={company,...BUSINESSES[company],enabled:false,chiefOnly:true,activatedAt:Date.now()-3600000,lines:BUSINESSES[company].phones.map((phone,i)=>({phone,instance:company+'-'+i}))},store=new Store(':memory:',company,randomBytes(32));return {config,store,engine:new Engine(store,config)};}
const event=(f,text,patch={})=>({id:'STATUS_TEST_001',phone:SANDRA,line:f.config.lines[0].phone,at:Date.now(),fromMe:false,kind:'text',text,quotedId:null,...patch});
test('actual screenshot questions answer mode and counts under pause without review acknowledgements or releases',async()=>{
 for(const text of ['maria angel, estas funcionando?','maria angel, estas respondiendo mensajes de ambas lineas?','maria angel, cuantos chats has respondido de ambas lineas de whatsapp?']){
  const f=fixture();try{const e=event(f,text);f.store.enqueue(e);f.store.hold(SANDRA,'STAFF_OWN_01',true);await f.engine.process(e);await f.engine.process(e);const rows=f.store.db.prepare('SELECT * FROM outbox').all();assert.equal(rows.length,1);assert.equal(rows[0].internal,1);assert.equal(rows[0].phone,SANDRA);assert.match(f.store.open(rows[0].body),/pausada/);assert.doesNotMatch(f.store.open(rows[0].body),/guardé tu solicitud|sigo en aprendizaje/);assert.equal(f.store.conversation(SANDRA).hold,1);assert.equal(f.store.db.prepare("SELECT name FROM sqlite_master WHERE name='chief_requests'").get(),undefined);}finally{f.store.close();}
 }
});
test('counts deduplicate both own lines and exclude staff, internal, missing MID, suppressed, unknown line and unverified delivery',()=>{
 const f=fixture();try{const now=Date.now(),rows=[['ONE','573001112233',0,'DELIVERED','MID1'],['TWO','573001112233',1,'READ','MID2'],['THREE','573004445566',0,'READ','MID3'],['UNCERTAIN','573007778899',1,'ACCEPTED','MID4'],['SUPPRESSED','573000001111',0,'SUPPRESSED_HUMAN','MID5'],['NO_MID','573000002222',0,'READ',null]];for(const[id,phone,i,state,mid]of rows){f.store.queue(id,phone,f.config.lines[i].phone,'Hola',false,0);f.store.db.prepare('UPDATE outbox SET state=?,mid=?,created=? WHERE id=?').run(state,mid,now-10,id);}f.store.queue('CHIEF_OUT',SANDRA,f.config.lines[0].phone,'Hola',true,0);f.store.db.prepare("UPDATE outbox SET state='READ',mid='CHIEF_MID' WHERE id='CHIEF_OUT'").run();
 f.store.enqueue(event(f,'Hola',{id:'STAFF_ONLY_01',phone:'573000003333',fromMe:true}));
 const a=customerActivity(f.store,f.config,false,now);assert.equal(a.deliveredChats,2);assert.deepEqual(a.lines.map(x=>x.deliveredChats),[2,1]);assert.equal(a.unverifiedDeliveryChats,1);assert.equal(a.staffRepliesIncluded,false);
 }finally{f.store.close();}
});
test('today uses Bogota midnight rather than UTC and does not attribute past replies to today',()=>{
 const f=fixture();try{const now=Date.parse('2026-10-03T18:30:00Z');for(const[id,at]of [['BEFORE',Date.parse('2026-10-03T04:59:59Z')],['TODAY',Date.parse('2026-10-03T05:00:00Z')]]){f.store.queue(id,id==='BEFORE'?'573001112233':'573004445566',f.config.lines[0].phone,'Hola',false,0);f.store.db.prepare("UPDATE outbox SET state='DELIVERED',mid=?,created=? WHERE id=?").run(id+'_MID',at,id);}assert.equal(customerActivity(f.store,f.config,true,now).deliveredChats,1);assert.equal(customerActivity(f.store,f.config,false,now).deliveredChats,2);}finally{f.store.close();}
});
test('quoted native question survives unrelated messageContextInfo and is answered only against own exact delivered MID',async()=>{
 const f=fixture();try{f.store.queue('OWN_QUESTION',SANDRA,f.config.lines[0].phone,'Estoy aquí',true,0);f.store.db.prepare("UPDATE outbox SET mid='OWN_REPLY_MID',state='READ'").run();const body={instance:f.config.lines[0].instance,event:'messages.upsert',data:{key:{id:'NATIVE_STATUS_01',fromMe:false,remoteJid:'231670619889791@lid',remoteJidAlt:SANDRA+'@s.whatsapp.net'},messageTimestamp:Math.floor(Date.now()/1000),message:{conversation:'estas repsondiendo mensajes?',messageContextInfo:{threadId:[]}},contextInfo:{stanzaId:'OWN_REPLY_MID'}}};const raw=decodeWebhook(body,f.config).events[0].event;assert.equal(raw.quotedId,'OWN_REPLY_MID');const e={...raw,line:f.config.lines[0].phone,at:Date.parse(raw.at)};f.store.enqueue(e);await f.engine.process(e);assert.equal(f.store.db.prepare('SELECT state FROM events WHERE id=?').get(e.id).state,'CHIEF_STATUS');assert.match(f.store.open(f.store.db.prepare('SELECT body FROM outbox WHERE id=?').get(e.id+':status').body),/pausada/);}finally{f.store.close();}
});
test('third-person, undirected, forwarded and a third party quoting a chief reply do not acquire authority',async()=>{
 const f=fixture();try{f.store.queue('OWN_QUESTION',SANDRA,f.config.lines[0].phone,'Estoy aquí',true,0);f.store.db.prepare("UPDATE outbox SET mid='OWN_REPLY_MID',state='READ'").run();for(const[i,patch]of [{text:'María Ángel dijo que está respondiendo mensajes'},{text:'estas respondiendo mensajes?'},{forwarded:true,text:'María Ángel, cuantos chats has respondido?'},{phone:'573009991111',quotedId:'OWN_REPLY_MID',text:'María Ángel, cuantos chats has respondido?'}].entries()){const e=event(f,'',{id:'NO_AUTH_'+i,...patch});f.store.enqueue(e);await f.engine.process(e);}assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM outbox').get().n,1);}finally{f.store.close();}
});
test('conflicting native citation cannot select a question and any forwarded marker stays forwarded',()=>{
 const f=fixture();try{const data={key:{id:'NATIVE_QUOTE_01',fromMe:false,remoteJid:SANDRA+'@s.whatsapp.net'},messageTimestamp:Math.floor(Date.now()/1000),message:{conversation:'estas respondiendo mensajes?',messageContextInfo:{stanzaId:'OTHER_REPLY',isForwarded:true}},contextInfo:{stanzaId:'OWN_REPLY_MID'}};const e=decodeWebhook({instance:f.config.lines[0].instance,event:'messages.upsert',data},f.config).events[0].event;assert.equal(e.quotedId,null);assert.equal(e.forwarded,true);}finally{f.store.close();}
});
test('status recognition never converts a question about actions, clients or campaigns into execution',()=>{
 for(const t of ['envia 300 mensajes a los clientes','cuantos chats has respondido y ahora envíales una promoción','estas respondiendo mensajes porque dije que no respondas','crea un servicio'])assert.equal(chiefStatusTopic(t),null);
 assert.equal(chiefStatusTopic('cuantos chats has respondido de ambas lineas de whatsapp?'),'counts');assert.equal(chiefStatusTopic('estas repsondiendo mensajes?'),'customer-status');
});
test('Miguel uses only his own stored scope and Diego gets the same factual status without changing human attention',async()=>{
 const f=fixture('servicio-tecnico');try{const e=event(f,'Miguel Ángel, estas respondiendo mensajes?',{phone:DIEGO});f.store.enqueue(e);f.store.hold(DIEGO,'STAFF_DIEGO',true);await f.engine.process(e);const row=f.store.db.prepare('SELECT * FROM outbox').get();assert.equal(row.phone,DIEGO);assert.match(f.store.open(row.body),/pausada/);assert.equal(f.store.conversation(DIEGO).hold,1);}finally{f.store.close();}
});
