import test from 'node:test';import assert from 'node:assert/strict';import {randomBytes} from 'node:crypto';
import {Store} from '../automation/service-bots/store.mjs';
import {BUSINESSES,SANDRA,DIEGO} from '../automation/service-bots/config.mjs';
import {chiefReadOnlyTopic,chiefReadOnlyReply,whatsAppCallActivity} from '../automation/service-bots/chief-readonly.mjs';

const NOW=Date.parse('2026-10-08T22:30:00Z'),QUERY='necesito que me digas cuantas llamadas han salido y entrado de las 2 lineas de whatsapp';
function fixture(company='fumigacion'){const config={company,...BUSINESSES[company],lines:BUSINESSES[company].phones.map(phone=>({phone}))},store=new Store(':memory:',company,randomBytes(32));return {config,store};}
function record(f,id,line,at,kind='call',fromMe=false){const e={id,line,at,phone:'573001112233',kind,fromMe,text:kind==='call'?'Llamada observada.':'Hola.'};f.store.enqueue(e);return e;}

test('natural directed body recognizes WhatsApp call record questions including the exact request',()=>{
 for(const text of [QUERY,'¿Cuántas llamadas han entrado y salido hoy de ambas líneas de WhatsApp?','Dime cuántas llamadas entrantes y salientes hay en las dos líneas de WhatsApp hoy.','Por favor dime el número de llamadas de WhatsApp','Me puedes decir cuántas llamadas recibidas hay en mis dos líneas, por favor?','Cuántas llamadas de las dos líneas?'])assert.equal(chiefReadOnlyTopic(text),'whatsapp-call-records',text);
});
test('OpenAI, chats, foreign destinations/companies, other periods and mixed commands are not this read request',()=>{
 for(const text of ['cuantas llamadas de OpenAI','cuantas llamadas de IA hay hoy','cuantos chats han entrado de las dos lineas de whatsapp','cuantas llamadas han salido de las dos lineas de whatsapp y crea un servicio','necesito que me digas cuantas llamadas han entrado de las dos lineas de whatsapp y cancela las citas','cuantas llamadas de las dos lineas de whatsapp y registra el pago','dile a Diego cuantas llamadas han entrado de las dos lineas de whatsapp','cuantas llamadas de las lineas de Abogados','cuantas llamadas han entrado de las dos lineas de whatsapp ayer','cuantas llamadas han entrado de las dos lineas de whatsapp en total','cuantas llamadas han entrado de la linea 573152819233','María dijo que necesito saber cuantas llamadas de las dos lineas'])assert.equal(chiefReadOnlyTopic(text),null,text);
 assert.equal(chiefReadOnlyTopic({text:QUERY}),null);
});
test('zero observed records states absence of sufficient history without reporting zero calls',()=>{const f=fixture();try{
 const activity=whatsAppCallActivity(f.store,f.config,NOW),reply=chiefReadOnlyReply(f.store,f.config,SANDRA,chiefReadOnlyTopic(QUERY),QUERY,NOW);assert.equal(activity.observedCallRecords,0);assert.match(reply,/no tengo historial de llamadas suficiente/);assert.match(reply,/No puedo afirmar que hayan sido cero/);assert.doesNotMatch(reply,/(?:0 llamadas|cero llamadas|entrantes: 0|salientes: 0)/);assert.equal(activity.totalCallsVerified,false);assert.equal(activity.fromMeDirectionUsed,false);
}finally{f.store.close();}});
test('observed call IDs use Bogotá day and own lines, exclude texts/AI-like metadata/future and foreign lines',()=>{const f=fixture();try{
 const [a,b]=f.config.lines.map(line=>line.phone);record(f,'CALL_A_ONE',a,Date.parse('2026-10-08T05:00:00Z'));record(f,'CALL_B_ONE',b,NOW-1000,'call',true);record(f,'CALL_PREVIOUS_DAY',a,Date.parse('2026-10-08T04:59:59Z'));record(f,'CALL_FUTURE',a,NOW+1);record(f,'FOREIGN_CALL',BUSINESSES['servicio-tecnico'].phones[0],NOW-1000);record(f,'NORMAL_TEXT_CALLS',a,NOW-1000,'text');record(f,'OPENAI_ANALYSIS',a,NOW-1000,'ai');
 const activity=whatsAppCallActivity(f.store,f.config,NOW);assert.equal(activity.date,'2026-10-08');assert.equal(activity.from,'2026-10-08T05:00:00.000Z');assert.equal(activity.observedCallRecords,2);assert.deepEqual(activity.lines.map(line=>line.observedCallRecords),[1,1]);assert.equal(activity.inboundOutboundVerified,false);assert.equal(activity.answeredCallsVerified,false);assert.equal(activity.durationVerified,false);
 const reply=chiefReadOnlyReply(f.store,f.config,SANDRA,'whatsapp-call-records',QUERY,NOW);assert.match(reply,/2 registros de llamadas observados/);assert.match(reply,/línea 4997: 1; línea 8721: 1/);assert.match(reply,/historial es parcial/);assert.match(reply,/no confirma el total real/);assert.doesNotMatch(reply,/1 entrante|1 saliente|realicé 2 llamadas/);
}finally{f.store.close();}});
test('same stored ID observed on both own lines is one unique record, never two proven WhatsApp calls',()=>{const f=fixture();try{
 const [a,b]=f.config.lines.map(line=>line.phone),e=record(f,'SAME_CALL_EVENT_ID',a,NOW-1000);f.store.enqueue({...e,line:b});record(f,'DISTINCT_CALL_EVENT_ID',a,NOW-500);f.store.db.prepare('INSERT INTO event_sources VALUES(?,?)').run(e.id,BUSINESSES['servicio-tecnico'].phones[0]);
 const activity=whatsAppCallActivity(f.store,f.config,NOW);assert.equal(activity.observedCallRecords,2);assert.deepEqual(activity.lines.map(line=>line.observedCallRecords),[2,1]);assert.equal(activity.duplicateLineObservations,1);assert.equal(activity.nativeCallIdentifiersVerified,false);assert.match(chiefReadOnlyReply(f.store,f.config,SANDRA,'whatsapp-call-records',QUERY,NOW),/ambas líneas se cuentan una sola vez/);
}finally{f.store.close();}});
test('reply is Sandra-only, store-scoped and read-only including holds, queue and audit',()=>{const f=fixture('servicio-tecnico');try{
 record(f,'TECHNICAL_CALL_ID',f.config.lines[0].phone,NOW-1000);f.store.enqueue({id:'CHIEF_READ_REQUEST',line:f.config.lines[0].phone,at:NOW,phone:SANDRA,kind:'text',fromMe:false,text:QUERY});f.store.hold(SANDRA,'STAFF_SOURCE',true);const before=['events','event_sources','conversations','outbox','questions','audit'].map(table=>JSON.stringify(f.store.db.prepare('SELECT * FROM '+table+' ORDER BY rowid').all()));
 assert.equal(chiefReadOnlyReply(f.store,f.config,DIEGO,'whatsapp-call-records',QUERY,NOW),null);assert.equal(chiefReadOnlyReply(f.store,f.config,SANDRA,'whatsapp-call-records','crea un servicio',NOW),null);assert.match(chiefReadOnlyReply(f.store,f.config,SANDRA,'whatsapp-call-records',QUERY,NOW),/línea 1941: 1; línea 9392: 0/);assert.equal(f.store.conversation(SANDRA).hold,1);
 assert.deepEqual(['events','event_sources','conversations','outbox','questions','audit'].map(table=>JSON.stringify(f.store.db.prepare('SELECT * FROM '+table+' ORDER BY rowid').all())),before);assert.throws(()=>whatsAppCallActivity(f.store,{...f.config,company:'fumigacion'},NOW),/DATABASE_SCOPE/);assert.throws(()=>whatsAppCallActivity(f.store,{...f.config,lines:[...f.config.lines.slice(0,1),{phone:BUSINESSES.fumigacion.phones[0]}]},NOW),/DATABASE_SCOPE/);
}finally{f.store.close();}});
test('unread or inconsistent stored events retain partial coverage without invented call counts',()=>{const f=fixture();try{
 record(f,'CORRUPT_CALL_EVENT',f.config.lines[0].phone,NOW-1000);f.store.db.prepare('UPDATE events SET body=? WHERE id=?').run('invalid encrypted body','CORRUPT_CALL_EVENT');const other=record(f,'INCONSISTENT_CALL_EVENT',f.config.lines[1].phone,NOW-1000);f.store.db.prepare('UPDATE events SET body=? WHERE id=?').run(f.store.seal({...other,id:'OTHER_ID'}),other.id);
 const activity=whatsAppCallActivity(f.store,f.config,NOW);assert.equal(activity.observedCallRecords,0);assert.equal(activity.unreadStoredRecords,2);assert.equal(activity.coverage,'partial-stored-event-observations');assert.match(chiefReadOnlyReply(f.store,f.config,SANDRA,'whatsapp-call-records',QUERY,NOW),/no tengo historial de llamadas suficiente/);
}finally{f.store.close();}});
